import os

app_path = os.path.join(os.path.dirname(__file__), "..", "app.js")

with open(app_path, "r", encoding="utf-8") as f:
    code = f.read()

# Replace the modal helpers and add generateMasterExcelWithAttendanceAndEmail
old_modal_section_start = "function openGitHubSyncModal() {"

new_helpers = """function generateMasterExcelWithAttendanceAndEmail() {
    const activeDate = getActiveDateString();
    
    // 1. Generate & download the complete populated Master Excel spreadsheet
    const wb = generateExportWorkbook();
    const filename = `TBTA-2026-2027- RHS-Student_Attendance_Master_${activeDate}.xlsx`;
    saveAndShareExcel(wb, filename);

    // 2. Draft comprehensive email summary
    let emailBody = `TBTA Attendance & Homework Master Report - ${activeDate}\\n`;
    emailBody += `===========================================\\n`;
    emailBody += `Generated by: System Administrator\\n`;
    emailBody += `Date: ${activeDate}\\n`;
    emailBody += `Spreadsheet: ${filename}\\n`;
    emailBody += `===========================================\\n\\n`;

    LOCATIONS.forEach(loc => {
        const locTeachers = appState.teachers.filter(t => t.Location === loc);
        const locStudents = appState.students.filter(s => s.Location === loc);

        const pT = locTeachers.filter(t => appState.attendance.Teachers[activeDate]?.[t.ID] === "present");
        const aT = locTeachers.filter(t => appState.attendance.Teachers[activeDate]?.[t.ID] === "absent");
        const pS = locStudents.filter(s => appState.attendance.Students[activeDate]?.[s.ID] === "present");
        const aS = locStudents.filter(s => appState.attendance.Students[activeDate]?.[s.ID] === "absent");

        emailBody += `📍 LOCATION: ${loc}\\n`;
        emailBody += `-------------------------------------------\\n`;
        emailBody += `- Teachers: Present: ${pT.length}/${locTeachers.length} | Absent: ${aT.length}/${locTeachers.length}\\n`;
        if (aT.length > 0) {
            emailBody += `  Absent Teachers: ${aT.map(t => t.Name).join(", ")}\\n`;
        }
        emailBody += `- Students: Present: ${pS.length}/${locStudents.length} | Absent: ${aS.length}/${locStudents.length}\\n`;
        if (aS.length > 0) {
            emailBody += `  Absent Students: ${aS.map(s => s.Name).join(", ")}\\n`;
        }
        emailBody += `\\n`;
        
        emailBody += `Class-by-Class Attendance Breakdown:\\n`;
        GRADES.forEach(g => {
            const classKids = locStudents.filter(s => s.Grade === g);
            const cp = classKids.filter(s => appState.attendance.Students[activeDate]?.[s.ID] === "present").length;
            const ca = classKids.filter(s => appState.attendance.Students[activeDate]?.[s.ID] === "absent").length;
            const cu = classKids.length - cp - ca;
            emailBody += `  • ${g.padEnd(12)}: Present: ${cp}/${classKids.length} | Absent: ${ca} | Unmarked: ${cu}\\n`;
        });
        emailBody += `\\n`;
    });

    emailBody += `===========================================\\n`;
    emailBody += `Attached/Downloaded: ${filename}\\n`;
    emailBody += `Live Google Sheets: https://docs.google.com/spreadsheets/\\n`;
    emailBody += `===========================================\\n`;

    const subject = encodeURIComponent(`TBTA Attendance & Homework Master Report - ${activeDate}`);
    const body = encodeURIComponent(emailBody);
    const mailtoUrl = `mailto:${TARGET_EMAIL}?subject=${subject}&body=${body}`;

    alert(`✅ Master Excel file "${filename}" generated and downloaded successfully!\\n\\nClick OK to open email draft with report summary.`);
    window.location.href = mailtoUrl;
}

function openGitHubSyncModal() {
    const modal = document.getElementById("github-sync-modal-overlay");
    if (modal) {
        modal.style.display = "flex";
        const gInput = document.getElementById("modal-gdrive-url-input");
        if (gInput && window.AttendanceSync) {
            gInput.value = window.AttendanceSync.getGoogleDriveUrl() || "";
        }
    }
}

function closeGitHubSyncModal(event) {
    if (event && event.target !== document.getElementById("github-sync-modal-overlay") && !event.target.classList.contains("modal-close-btn") && event.target.tagName !== "BUTTON") return;
    const modal = document.getElementById("github-sync-modal-overlay");
    if (modal) modal.style.display = "none";
}

function saveGoogleDriveUrlFromModal() {
    const input = document.getElementById("modal-gdrive-url-input");
    if (!input || !window.AttendanceSync) return;
    const url = input.value.trim();
    window.AttendanceSync.setGoogleDriveUrl(url);
    alert(url ? "✅ Google Drive & Sheets Webhook URL saved successfully!" : "Google Drive URL cleared.");
    testGoogleDriveConnectionModal();
}

async function testGoogleDriveConnectionModal() {
    if (!window.AttendanceSync) return;
    const statusDiv = document.getElementById("modal-gdrive-status");
    if (statusDiv) statusDiv.textContent = "Testing connection to Google Drive & Sheets...";
    const res = await window.AttendanceSync.testConnection();
    if (statusDiv) {
        statusDiv.textContent = (res.success ? "✅ " : "❌ ") + res.message;
        statusDiv.style.color = res.success ? "var(--success-color)" : "var(--danger-color)";
    }
    alert((res.success ? "✅ " : "❌ ") + res.message);
}

async function forceSyncFromCloud() {
    if (!window.AttendanceSync) return;
    try {
        const shared = await window.AttendanceSync.load();
        if (shared) {
            applyPersistedState(shared, false);
            renderList();
            alert("✅ Successfully pulled latest attendance from Google Sheets!");
        } else {
            alert("No remote state found in Google Sheets.");
        }
    } catch (e) {
        alert("Could not load from Google Sheets: " + e.message);
    }
}

async function forcePushToCloud() {
    if (!window.AttendanceSync) return;
    try {
        await window.AttendanceSync.forceSync(getSharedPersistedState());
        alert("✅ Synced local data to Google Sheets & Google Drive!");
    } catch (e) {
        alert("Sync failed: " + e.message);
    }
}
"""

if old_modal_section_start in code:
    idx = code.find(old_modal_section_start)
    code = code[:idx] + new_helpers

with open(app_path, "w", encoding="utf-8") as f:
    f.write(code)

print("Successfully updated app.js with generateMasterExcelWithAttendanceAndEmail and clean modal handlers")
